/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/hdts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List HDTs
         * @description Returns all Human Digital Twins
         */
        get: operations["hdts/get"];
        put?: never;
        /**
         * Create HDT
         * @description Creates a new Human Digital Twin
         */
        post: operations["hdts/post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get HDT
         * @description Get a Human Digital Twin by its ID
         */
        get: operations["hdts/{id}/get"];
        /**
         * Update HDT
         * @description Update a Human Digital Twin
         */
        put: operations["hdts/{id}/update"];
        post?: never;
        /**
         * Remove HDT
         * @description Remove a Human Digital Twin
         */
        delete: operations["hdts/{id}/remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get HDT's Models
         * @description Get all Models of the specified HDT
         */
        get: operations["hdts/{id}/models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get HDT's [Events]
         * @description Get all Events of the specified HDT
         */
        get: operations["hdts/{id}/events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Batch update [HDT]
         * @description Update a list of Human Digital Twins
         */
        put: operations["hdts/batch/update"];
        /**
         * Batch insert [HDT]
         * @description Insert a list of Human Digital Twins
         */
        post: operations["hdts/batch/insert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Return all Models
         */
        get: operations["models/get"];
        /**
         * Create or Update Model
         * @description Creates a new Model or updates it if already exists
         */
        put: operations["models/upsert"];
        /**
         * Create Model
         * @description Creates a new model
         */
        post: operations["models/create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Batch upsert [Model]
         * @description Insert or update a list of HDT Models
         */
        put: operations["models/batch/upsert"];
        /**
         * Batch insert [Model]
         * @description Insert a list of HDT Models
         */
        post: operations["models/batch/insert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * properties/insert
         * @description Batch insert HDT's [Property] as Events
         */
        post: operations["properties/insert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/values/valuesById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Events by Id */
        post: operations["query/event/values/byId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/values/valuesByName": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Events by Name */
        post: operations["query/event/values/byName"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/values/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Event history for a certain HDT */
        post: operations["query/event/values/history"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Aggregate Stats */
        post: operations["query/event/stats"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Events by comparisons */
        post: operations["query/event/comparison"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PropertyComparisonDto: {
            propertyName: string;
            /** @enum {string} */
            comparison: "GT" | "GTE" | "LT" | "LTE" | "EQ";
            value: number | string | boolean;
        };
        PropertiesByComparisonsRequestDto: {
            comparisons: components["schemas"]["PropertyComparisonDto"][];
            modelNames?: string[] | null;
            /** Format: date-time */
            from?: string | null;
            /** Format: date-time */
            to?: string | null;
        };
        /** mqtt-physical-interface */
        "mqtt-physical-interface": {
            hdtId: string;
            name: string;
            broker?: string;
            port?: number;
            config?: {
                [key: string]: string;
            };
            /** @enum {string} */
            interfaceType?: "MQTT";
            id?: string;
        };
        /** physical-interface-impl */
        "physical-interface-impl": {
            /** @enum {string} */
            interfaceType: "MQTT";
            hdtId: string;
            name: string;
            config?: {
                [key: string]: string;
            };
            id?: string;
        };
        /** io.github.whdt.core.hdt.interfaces.physical.PhysicalInterface */
        PhysicalInterface: components["schemas"]["mqtt-physical-interface"] | components["schemas"]["physical-interface-impl"];
        /** digital-interface-impl */
        "digital-interface-impl": {
            /** @enum {string} */
            interfaceType: "MQTT" | "HTTP";
            hdtId: string;
            name: string;
            config?: {
                [key: string]: string;
            };
            id?: string;
        };
        /** http-digital-interface */
        "http-digital-interface": {
            hdtId: string;
            name: string;
            host?: string;
            port?: number;
            config?: {
                [key: string]: string;
            };
            /** @enum {string} */
            interfaceType?: "HTTP";
            id?: string;
        };
        /** mqtt-digital-interface */
        "mqtt-digital-interface": {
            hdtId: string;
            name: string;
            broker?: string;
            port?: number;
            config?: {
                [key: string]: string;
            };
            /** @enum {string} */
            interfaceType?: "MQTT";
            id?: string;
        };
        /** io.github.whdt.core.hdt.interfaces.digital.DigitalInterface */
        DigitalInterface: components["schemas"]["digital-interface-impl"] | components["schemas"]["http-digital-interface"] | components["schemas"]["mqtt-digital-interface"];
        /** io.github.whdt.core.hdt.storage.Storage */
        Storage: {
            hdtId: string;
            name: string;
            /** @enum {string} */
            storageType: "IN_MEMORY" | "DB_MONGO" | "DB_POSTGRESQL";
            id?: string;
        };
        /** io.github.whdt.db.hdt.HumanDigitalTwinDocument */
        HumanDigitalTwinDocument: {
            hdtId: string;
            physicalInterfaces: components["schemas"]["PhysicalInterface"][];
            digitalInterfaces: components["schemas"]["DigitalInterface"][];
            storages: components["schemas"]["Storage"][];
        };
        /** model */
        model: {
            hdtId: string;
            name: string;
            description: string;
            properties: components["schemas"]["property"][];
            id?: string;
        };
        /** human-digital-twin */
        "human-digital-twin": {
            hdtId: string;
            models?: components["schemas"]["model"][];
            physicalInterfaces?: components["schemas"]["PhysicalInterface"][];
            digitalInterfaces?: components["schemas"]["DigitalInterface"][];
            storages?: components["schemas"]["Storage"][];
        };
        /** io.github.whdt.db.model.ModelDocument */
        ModelDocument: {
            hdtId: string;
            modelId: string;
            modelName: string;
            modelDescription: string;
            /** Format: date-time */
            lastUpdated?: string;
        };
        /** io.github.whdt.db.property.PropertyEventMetadata */
        PropertyEventMetadata: {
            hdtId: string;
            modelId: string;
            modelName: string;
            propertyName: string;
            propertyId: string;
        };
        /** boolean-value */
        "boolean-value": {
            value: boolean;
        };
        /** double-value */
        "double-value": {
            value: number;
        };
        /** empty-value */
        "empty-value": Record<string, never>;
        /** float-value */
        "float-value": {
            value: number;
        };
        /** int-value */
        "int-value": {
            value: number;
        };
        /** long-value */
        "long-value": {
            value: number;
        };
        /** string-value */
        "string-value": {
            value: string;
        };
        /** io.github.whdt.core.hdt.model.property.PropertyValue */
        PropertyValue: components["schemas"]["boolean-value"] | components["schemas"]["double-value"] | components["schemas"]["empty-value"] | components["schemas"]["float-value"] | components["schemas"]["int-value"] | components["schemas"]["long-value"] | components["schemas"]["string-value"];
        /** io.github.whdt.db.property.PropertyEventDocument */
        PropertyEventDocument: {
            metaField: components["schemas"]["PropertyEventMetadata"];
            /** Format: date-time */
            timeField: string;
            value: components["schemas"]["PropertyValue"];
        };
        /** property */
        property: {
            modelId: string;
            name: string;
            description: string;
            /** Format: date-time */
            timestamp: string;
            value: components["schemas"]["PropertyValue"];
            id?: string;
        };
        /** io.github.whdt.routing.query.event.values.PropertyValuesRequest */
        PropertyValuesRequest: {
            hdtId?: string;
            modelId?: string;
            propertyId?: string;
            propertyName?: string;
            /** Format: date-time */
            from?: string | null;
            /** Format: date-time */
            to?: string | null;
        };
        /** io.github.whdt.routing.query.event.stats.PropertyStatsRequest */
        PropertyStatsRequest: {
            hdtIds: string[];
            modelIds: string[];
            modelNames: string[];
            propertyName: string;
            /** Format: date-time */
            from?: string | null;
            /** Format: date-time */
            to?: string | null;
        };
        /** io.github.whdt.routing.query.event.stats.PropertyStatsPerHdt */
        PropertyStatsPerHdt: {
            hdtId: string;
            count: number;
            avg?: number | null;
            min?: number | null;
            max?: number | null;
        };
        /** io.github.whdt.routing.query.event.comparison.PropertyComparison */
        PropertyComparison: {
            propertyName: string;
            /** @enum {string} */
            comparison: "GT" | "GTE" | "LT" | "LTE" | "EQ";
            value: components["schemas"]["PropertyValue"];
        };
        /** io.github.whdt.routing.query.event.comparison.PropertiesByComparisonsAggregateRequest */
        PropertiesByComparisonsAggregateRequest: {
            comparisons: components["schemas"]["PropertyComparison"][];
            modelNames?: string[] | null;
            /** Format: date-time */
            from?: string | null;
            /** Format: date-time */
            to?: string | null;
        };
        /** io.github.whdt.routing.query.event.comparison.EventMatch */
        EventMatch: {
            propertyName: string;
            value: components["schemas"]["PropertyValue"];
            /** Format: date-time */
            timeField: string;
        };
        /** io.github.whdt.routing.query.event.comparison.PropertiesByComparisonsAggregateResponse */
        PropertiesByComparisonsAggregateResponse: {
            hdtId: string;
            matchedProperties: string[];
            matchedEvents: components["schemas"]["EventMatch"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type PropertyComparisonDto = components['schemas']['PropertyComparisonDto'];
export type PropertiesByComparisonsRequestDto = components['schemas']['PropertiesByComparisonsRequestDto'];
export type MqttPhysicalInterface = components['schemas']['mqtt-physical-interface'];
export type PhysicalInterfaceImpl = components['schemas']['physical-interface-impl'];
export type PhysicalInterface = components['schemas']['PhysicalInterface'];
export type DigitalInterfaceImpl = components['schemas']['digital-interface-impl'];
export type HttpDigitalInterface = components['schemas']['http-digital-interface'];
export type MqttDigitalInterface = components['schemas']['mqtt-digital-interface'];
export type DigitalInterface = components['schemas']['DigitalInterface'];
export type Storage = components['schemas']['Storage'];
export type HumanDigitalTwinDocument = components['schemas']['HumanDigitalTwinDocument'];
export type Model = components['schemas']['model'];
export type HumanDigitalTwin = components['schemas']['human-digital-twin'];
export type ModelDocument = components['schemas']['ModelDocument'];
export type PropertyEventMetadata = components['schemas']['PropertyEventMetadata'];
export type BooleanValue = components['schemas']['boolean-value'];
export type DoubleValue = components['schemas']['double-value'];
export type EmptyValue = components['schemas']['empty-value'];
export type FloatValue = components['schemas']['float-value'];
export type IntValue = components['schemas']['int-value'];
export type LongValue = components['schemas']['long-value'];
export type StringValue = components['schemas']['string-value'];
export type PropertyValue = components['schemas']['PropertyValue'];
export type PropertyEventDocument = components['schemas']['PropertyEventDocument'];
export type Property = components['schemas']['property'];
export type PropertyValuesRequest = components['schemas']['PropertyValuesRequest'];
export type PropertyStatsRequest = components['schemas']['PropertyStatsRequest'];
export type PropertyStatsPerHdt = components['schemas']['PropertyStatsPerHdt'];
export type PropertyComparison = components['schemas']['PropertyComparison'];
export type PropertiesByComparisonsAggregateRequest = components['schemas']['PropertiesByComparisonsAggregateRequest'];
export type EventMatch = components['schemas']['EventMatch'];
export type PropertiesByComparisonsAggregateResponse = components['schemas']['PropertiesByComparisonsAggregateResponse'];
export type $defs = Record<string, never>;
export interface operations {
    "hdts/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All Human Digital Twins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanDigitalTwinDocument"][];
                };
            };
        };
    };
    "hdts/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The Representation of a Human Digital Twin */
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"];
            };
        };
        responses: {
            /** @description HumanDigitalTwin created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanDigitalTwinDocument"];
                };
            };
        };
    };
    "hdts/{id}/get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human Digital Twin found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanDigitalTwinDocument"];
                };
            };
            /** @description Human Digital Twin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Human Digital Twin */
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"];
            };
        };
        responses: {
            /** @description Human Digital Twin updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanDigitalTwinDocument"];
                };
            };
            /** @description Human Digital Twin to update not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human Digital Twin removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Human Digital Twin to remove not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human Digital Twin Models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDocument"][];
                };
            };
            /** @description Human Digital Twin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human Digital Twin Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyEventDocument"][];
                };
            };
            /** @description Human Digital Twin or Events not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/batch/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"][];
            };
        };
        responses: {
            /** @description Human Digital Twins updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Update failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/batch/insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"][];
            };
        };
        responses: {
            /** @description Human Digital Twins inserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insertion failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "models/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All Models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDocument"][];
                };
            };
        };
    };
    "models/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The updated Model */
        requestBody: {
            content: {
                "application/json": components["schemas"]["model"];
            };
        };
        responses: {
            /** @description Upserted Successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to upsert Model */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "models/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The representation of an HDT's Model */
        requestBody: {
            content: {
                "application/json": components["schemas"]["model"];
            };
        };
        responses: {
            /** @description Created Successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDocument"];
                };
            };
        };
    };
    "models/batch/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The list of HDT Models */
        requestBody: {
            content: {
                "application/json": components["schemas"]["model"][];
            };
        };
        responses: {
            /** @description Upserted Successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to upsert Models */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "models/batch/insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The list of HDT Models */
        requestBody: {
            content: {
                "application/json": components["schemas"]["model"][];
            };
        };
        responses: {
            /** @description Created Successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to create Models */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "properties/insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A Human Digital Twin */
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"];
            };
        };
        responses: {
            /** @description HDT's [Property] created as Events */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error creating Events */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/event/values/byId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyValuesRequest"][];
            };
        };
        responses: {
            /** @description POST /query/event/values/valuesById response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyEventDocument"][];
                };
            };
            /** @description POST /query/event/values/valuesById response 400 if empty request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/event/values/byName": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyValuesRequest"][];
            };
        };
        responses: {
            /** @description POST /query/event/values/valuesByName response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyEventDocument"][];
                };
            };
            /** @description POST /query/event/values/valuesByName response 400 if empty request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/event/values/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyValuesRequest"][];
            };
        };
        responses: {
            /** @description POST /query/event/values/history response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyEventDocument"][];
                };
            };
            /** @description POST /query/event/values/history response 400 if empty request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/event/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyStatsRequest"];
            };
        };
        responses: {
            /** @description POST /query/event/stats response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyStatsPerHdt"][];
                };
            };
        };
    };
    "query/event/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PropertiesByComparisonsRequestDto"];
            };
        };
        responses: {
            /** @description POST /query/event/comparison response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertiesByComparisonsAggregateResponse"];
                };
            };
        };
    };
}
