/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/hdts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List HDTs
         * @description Returns all Human Digital Twins
         */
        get: operations["hdts/get"];
        /**
         * Create or Update HDT
         * @description Creates a new Human Digital Twin or updates an existing one
         */
        put: operations["hdts/put"];
        /**
         * Create HDT
         * @description Creates a new Human Digital Twin
         */
        post: operations["hdts/post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get HDT
         * @description Get a Human Digital Twin by its ID
         */
        get: operations["hdts/{id}/get"];
        /**
         * Update HDT
         * @description Update a Human Digital Twin
         */
        put: operations["hdts/{id}/update"];
        post?: never;
        /**
         * Remove HDT
         * @description Remove a Human Digital Twin
         */
        delete: operations["hdts/{id}/remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get HDT's Models
         * @description Get all Models of the specified HDT
         */
        get: operations["hdts/{id}/models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get HDT's [Observations]
         * @description Get all Observations of the specified HDT
         */
        get: operations["hdts/{id}/observations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full HDT spec
         * @description Assembles a full HDT spec from hdt, models, and properties collections
         */
        get: operations["hdts/{id}/spec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/snapshot/by-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * By-task property snapshot
         * @description Latest observed value per (property, task) for the specified HDT. A property appears under each task in which it was observed. 'task' is null for observations recorded without a task.
         */
        get: operations["hdts/snapshot/by-task"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get HDT snapshot
         * @description Returns current value per property — latest observation or initialValue fallback
         */
        get: operations["hdts/{id}/snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Batch update [HDT]
         * @description Update a list of Human Digital Twins
         */
        put: operations["hdts/batch/update"];
        /**
         * Batch insert [HDT]
         * @description Insert a list of Human Digital Twins
         */
        post: operations["hdts/batch/insert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Return all Models
         */
        get: operations["models/get"];
        /**
         * Create or Update Model
         * @description Creates a new Model or updates it if already exists
         */
        put: operations["models/upsert"];
        /**
         * Create Model
         * @description Creates a new model
         */
        post: operations["models/create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Batch upsert [Model]
         * @description Insert or update a list of HDT Models
         */
        put: operations["models/batch/upsert"];
        /**
         * Batch insert [Model]
         * @description Insert a list of HDT Models
         */
        post: operations["models/batch/insert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Property specs
         * @description Return property specs for the specified HDT, optionally filtered by modelId
         */
        get: operations["properties/get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/properties/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch upsert Property specs
         * @description Insert or update a list of Property specs for the specified HDT
         */
        post: operations["properties/batch/upsert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hdts/{id}/properties/{propertyId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace Property tags
         * @description Replaces the entire tag map of a single Property spec. The request body is the complete desired tag map; an empty object clears all tags.
         */
        put: operations["properties/{propertyId}/tags/put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List distinct Property names
         * @description Returns the distinct set of propertyName values across all Property specs
         */
        get: operations["properties/names"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/observations/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch insert [PropertyObservation]
         * @description Batch insert PropertyObservation
         */
        post: operations["observations/batch/insert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/property": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Property specs by tag predicate
         * @description Returns Property specs whose tags satisfy the given TagPredicate.
         */
        post: operations["query/property"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/values/valuesById": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Observations by Id */
        post: operations["query/event/values/byId"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/values/valuesByName": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Observations by Name */
        post: operations["query/event/values/byName"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/values/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Observation history for a certain HDT */
        post: operations["query/event/values/history"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Aggregate Stats */
        post: operations["query/event/stats"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Views
         * @description Returns all stored Views
         */
        get: operations["views/get"];
        put?: never;
        /**
         * Create View
         * @description Creates or replaces a View by name
         */
        post: operations["views/post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get View
         * @description Get a View by name
         */
        get: operations["views/{name}/get"];
        /**
         * Upsert View
         * @description Create or replace a View by name (path name takes precedence)
         */
        put: operations["views/{name}/put"];
        post?: never;
        /**
         * Delete View
         * @description Delete a View by name
         */
        delete: operations["views/{name}/delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/{name}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute View
         * @description Run a stored View against HDTs. Empty or absent hdtIds executes against all HDTs.
         */
        post: operations["views/{name}/execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/event/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Observations by comparisons */
        post: operations["query/event/comparison"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/cohort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query cohort frame (per-DT values + stats + population summary) by comparisons */
        post: operations["query/cohort"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/hdts/by-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** List HDTs having raw observation data for the given models */
        post: operations["query/hdts/by-model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** io.github.whdt.core.hdt.query.TagPredicate */
        TagPredicate: components["schemas"]["TagPredicate-eq"] | components["schemas"]["TagPredicate-in"] | components["schemas"]["TagPredicate-has"] | components["schemas"]["TagPredicate-and"] | components["schemas"]["TagPredicate-or"] | components["schemas"]["TagPredicate-not"];
        /** TagPredicate-eq */
        "TagPredicate-eq": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "eq";
            key: string;
            value: string;
        };
        /** TagPredicate-in */
        "TagPredicate-in": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "in";
            key: string;
            values: string[];
        };
        /** TagPredicate-has */
        "TagPredicate-has": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "has";
            key: string;
        };
        /** TagPredicate-and */
        "TagPredicate-and": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "and";
            terms: components["schemas"]["TagPredicate"][];
        };
        /** TagPredicate-or */
        "TagPredicate-or": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "or";
            terms: components["schemas"]["TagPredicate"][];
        };
        /** TagPredicate-not */
        "TagPredicate-not": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "not";
            term: components["schemas"]["TagPredicate"];
        };
        PropertyComparisonDto: {
            propertyName: string;
            /** @enum {string} */
            comparison: "GT" | "GTE" | "LT" | "LTE" | "EQ";
            value: number | string | boolean;
        };
        PropertiesByComparisonsRequestDto: {
            comparisons: components["schemas"]["PropertyComparisonDto"][];
            modelNames?: string[] | null;
            /** Format: date-time */
            from?: string | null;
            /** Format: date-time */
            to?: string | null;
            metadataFilters?: {
                [key: string]: string[];
            } | null;
        };
        /** mqtt-physical-interface */
        "mqtt-physical-interface": {
            hdtId: string;
            name: string;
            broker?: string;
            port?: number;
            config?: {
                [key: string]: string;
            };
            /** @enum {string} */
            interfaceType?: "MQTT";
            id?: string;
        };
        /** physical-interface-impl */
        "physical-interface-impl": {
            /** @enum {string} */
            interfaceType: "MQTT";
            hdtId: string;
            name: string;
            config?: {
                [key: string]: string;
            };
            id?: string;
        };
        /** io.github.whdt.core.hdt.interfaces.physical.PhysicalInterface */
        PhysicalInterface: components["schemas"]["mqtt-physical-interface"] | components["schemas"]["physical-interface-impl"];
        /** digital-interface-impl */
        "digital-interface-impl": {
            /** @enum {string} */
            interfaceType: "MQTT" | "HTTP";
            hdtId: string;
            name: string;
            config?: {
                [key: string]: string;
            };
            id?: string;
        };
        /** http-digital-interface */
        "http-digital-interface": {
            hdtId: string;
            name: string;
            host?: string;
            port?: number;
            config?: {
                [key: string]: string;
            };
            /** @enum {string} */
            interfaceType?: "HTTP";
            id?: string;
        };
        /** mqtt-digital-interface */
        "mqtt-digital-interface": {
            hdtId: string;
            name: string;
            broker?: string;
            port?: number;
            config?: {
                [key: string]: string;
            };
            /** @enum {string} */
            interfaceType?: "MQTT";
            id?: string;
        };
        /** io.github.whdt.core.hdt.interfaces.digital.DigitalInterface */
        DigitalInterface: components["schemas"]["digital-interface-impl"] | components["schemas"]["http-digital-interface"] | components["schemas"]["mqtt-digital-interface"];
        /** io.github.whdt.core.hdt.storage.Storage */
        Storage: {
            hdtId: string;
            name: string;
            /** @enum {string} */
            storageType: "IN_MEMORY" | "DB_MONGO" | "DB_POSTGRESQL";
            id?: string;
        };
        /** io.github.whdt.db.hdt.HumanDigitalTwinDocument */
        HumanDigitalTwinDocument: {
            hdtId: string;
            physicalInterfaces: components["schemas"]["PhysicalInterface"][];
            digitalInterfaces: components["schemas"]["DigitalInterface"][];
            storages: components["schemas"]["Storage"][];
            tags?: {
                [key: string]: string;
            };
        };
        /** model */
        model: {
            hdtId: string;
            name: string;
            description: string;
            properties: components["schemas"]["property"][];
            id?: string;
            tags?: {
                [key: string]: string;
            };
            format?: string;
        };
        /** human-digital-twin */
        "human-digital-twin": {
            hdtId: string;
            models?: components["schemas"]["model"][];
            physicalInterfaces?: components["schemas"]["PhysicalInterface"][];
            digitalInterfaces?: components["schemas"]["DigitalInterface"][];
            storages?: components["schemas"]["Storage"][];
            tags?: {
                [key: string]: string;
            };
        };
        /** io.github.whdt.db.model.ModelDocument */
        ModelDocument: {
            hdtId: string;
            modelId: string;
            modelName: string;
            modelDescription: string;
            tags?: {
                [key: string]: string;
            };
            format?: string;
            /** Format: date-time */
            lastUpdated?: string;
        };
        /** io.github.whdt.db.property.PropertyDocument */
        PropertyDocument: {
            hdtId: string;
            modelId: string;
            propertyId: string;
            propertyName: string;
            description: string;
            /** @enum {string} */
            declaredType: "INT" | "LONG" | "FLOAT" | "DOUBLE" | "STRING" | "BOOLEAN";
            initialValue?: components["schemas"]["PropertyValue"];
            tags?: {
                [key: string]: string;
            };
            coding?: components["schemas"]["Coding"];
            ordinal?: number;
            /** Format: date-time */
            lastUpdated?: string;
        };
        /** io.github.whdt.db.property.PropertyEventMetadata */
        PropertyEventMetadata: {
            hdtId: string;
            modelId: string;
            modelName: string;
            propertyName: string;
            propertyId: string;
        };
        /** boolean-value */
        "boolean-value": {
            value: boolean;
        };
        /** double-value */
        "double-value": {
            value: number;
        };
        /** empty-value */
        "empty-value": Record<string, never>;
        /** float-value */
        "float-value": {
            value: number;
        };
        /** int-value */
        "int-value": {
            value: number;
        };
        /** long-value */
        "long-value": {
            value: number;
        };
        /** string-value */
        "string-value": {
            value: string;
        };
        /** io.github.whdt.core.hdt.model.property.PropertyValue */
        PropertyValue: components["schemas"]["boolean-value"] | components["schemas"]["double-value"] | components["schemas"]["empty-value"] | components["schemas"]["float-value"] | components["schemas"]["int-value"] | components["schemas"]["long-value"] | components["schemas"]["string-value"];
        /** io.github.whdt.core.hdt.model.property.Coding */
        Coding: {
            system: string;
            code: string;
        };
        /** io.github.whdt.db.property.PropertyObservationDocument */
        PropertyObservationDocument: {
            metaField: components["schemas"]["PropertyEventMetadata"];
            /** Format: date-time */
            timeField: string;
            value: components["schemas"]["PropertyValue"];
            metadata: {
                [key: string]: string;
            };
        };
        /** io.github.whdt.core.hdt.model.property.PropertyObservation */
        PropertyObservation: {
            hdtId: string;
            modelId: string;
            propertyId: string;
            propertyName: string;
            value: components["schemas"]["PropertyValue"];
            /** Format: date-time */
            timestamp: string;
            metadata?: {
                [key: string]: string;
            };
        };
        /** property */
        property: {
            modelId: string;
            name: string;
            description: string;
            /** @enum {string} */
            declaredType: "INT" | "LONG" | "FLOAT" | "DOUBLE" | "STRING" | "BOOLEAN";
            initialValue?: components["schemas"]["PropertyValue"];
            id?: string;
            tags?: {
                [key: string]: string;
            };
            coding?: components["schemas"]["Coding"];
            ordinal?: number;
        };
        /** io.github.whdt.db.assembler.PropertySpecEntry */
        PropertySpecEntry: {
            propertyId: string;
            propertyName: string;
            description: string;
            declaredType: string;
            initialValue?: components["schemas"]["PropertyValue"];
            tags?: {
                [key: string]: string;
            };
            coding?: components["schemas"]["Coding"];
            ordinal?: number;
        };
        /** io.github.whdt.db.assembler.ModelSpecEntry */
        ModelSpecEntry: {
            modelId: string;
            modelName: string;
            properties: components["schemas"]["PropertySpecEntry"][];
            tags?: {
                [key: string]: string;
            };
            format?: string;
        };
        /** io.github.whdt.db.assembler.HdtSpecResponse */
        HdtSpecResponse: {
            hdtId: string;
            physicalInterfaces: components["schemas"]["PhysicalInterface"][];
            digitalInterfaces: components["schemas"]["DigitalInterface"][];
            storages: components["schemas"]["Storage"][];
            models: components["schemas"]["ModelSpecEntry"][];
            tags: {
                [key: string]: string;
            };
        };
        /** io.github.whdt.db.assembler.PropertySnapshotEntry */
        PropertySnapshotEntry: {
            propertyId: string;
            propertyName: string;
            value?: components["schemas"]["PropertyValue"];
            /** Format: date-time */
            timestamp?: string | null;
            /** @enum {string} */
            source: "observation" | "initial_value";
        };
        /** io.github.whdt.db.assembler.TaskPropertySnapshotEntry */
        TaskPropertySnapshotEntry: {
            task?: string | null;
            propertyId: string;
            propertyName: string;
            modelName: string;
            value: components["schemas"]["PropertyValue"];
            /** Format: date-time */
            timestamp: string;
        };
        /** io.github.whdt.routing.query.event.values.PropertyValuesRequest */
        PropertyValuesRequest: {
            hdtId?: string;
            modelId?: string;
            propertyId?: string;
            propertyName?: string;
            /** Format: date-time */
            from?: string | null;
            /** Format: date-time */
            to?: string | null;
        };
        /** io.github.whdt.routing.query.event.stats.PropertyStatsRequest */
        PropertyStatsRequest: {
            hdtIds: string[];
            modelIds: string[];
            modelNames: string[];
            propertyName: string;
            /** Format: date-time */
            from?: string | null;
            /** Format: date-time */
            to?: string | null;
        };
        /** io.github.whdt.routing.query.event.stats.PropertyStatsPerHdt */
        PropertyStatsPerHdt: {
            hdtId: string;
            count: number;
            avg?: number | null;
            min?: number | null;
            max?: number | null;
        };
        /** io.github.whdt.routing.query.event.comparison.PropertyComparison */
        PropertyComparison: {
            propertyName: string;
            /** @enum {string} */
            comparison: "GT" | "GTE" | "LT" | "LTE" | "EQ";
            value: components["schemas"]["PropertyValue"];
        };
        /** io.github.whdt.routing.query.event.comparison.PropertiesByComparisonsAggregateRequest */
        PropertiesByComparisonsAggregateRequest: {
            comparisons: components["schemas"]["PropertyComparison"][];
            modelNames?: string[] | null;
            /** Format: date-time */
            from?: string | null;
            /** Format: date-time */
            to?: string | null;
        };
        /** io.github.whdt.routing.query.event.comparison.EventMatch */
        EventMatch: {
            propertyName: string;
            value: components["schemas"]["PropertyValue"];
            /** Format: date-time */
            timeField: string;
        };
        /** io.github.whdt.routing.query.event.comparison.PropertiesByComparisonsAggregateResponse */
        PropertiesByComparisonsAggregateResponse: {
            hdtId: string;
            matchedProperties: string[];
            matchedEvents: components["schemas"]["EventMatch"][];
        };
        /** io.github.whdt.routing.query.event.comparison.PropertyPopulationStats */
        PropertyPopulationStats: {
            propertyName: string;
            count: number;
            avg?: number | null;
            min?: number | null;
            max?: number | null;
            median?: number | null;
            p25?: number | null;
            p75?: number | null;
        };
        /** io.github.whdt.routing.query.event.comparison.ComparisonSearchResult */
        ComparisonSearchResult: {
            matches: components["schemas"]["PropertiesByComparisonsAggregateResponse"][];
            populationStats: components["schemas"]["PropertyPopulationStats"][];
        };
        /** io.github.whdt.routing.query.event.cohort.CohortPropertyCell */
        CohortPropertyCell: {
            propertyName: string;
            value?: components["schemas"]["PropertyValue"];
            count: number;
            avg?: number | null;
            min?: number | null;
            max?: number | null;
            median?: number | null;
            p25?: number | null;
            p75?: number | null;
        };
        /** io.github.whdt.routing.query.event.cohort.CohortRow */
        CohortRow: {
            hdtId: string;
            properties: components["schemas"]["CohortPropertyCell"][];
        };
        /** io.github.whdt.routing.query.event.cohort.CohortResult */
        CohortResult: {
            rows: components["schemas"]["CohortRow"][];
            populationStats: components["schemas"]["PropertyPopulationStats"][];
        };
        /** io.github.whdt.routing.query.availability.HdtsByModelRequestDto */
        HdtsByModelRequestDto: {
            modelNames?: string[] | null;
            /** @enum {string} */
            match?: "ANY" | "ALL";
            metadataFilters?: {
                [key: string]: string[];
            } | null;
            /** Format: date-time */
            from?: string | null;
            /** Format: date-time */
            to?: string | null;
        };
        /** io.github.whdt.routing.query.availability.ModelAvailability */
        ModelAvailability: {
            modelName: string;
            observationCount: number;
            /** Format: date-time */
            firstTimestamp: string;
            /** Format: date-time */
            lastTimestamp: string;
        };
        /** io.github.whdt.routing.query.availability.HdtModelAvailability */
        HdtModelAvailability: {
            hdtId: string;
            models: components["schemas"]["ModelAvailability"][];
        };
        /** io.github.whdt.core.hdt.view.View */
        View: {
            name: string;
            predicate?: components["schemas"]["TagPredicate"];
            groupByKeys?: string[];
        };
        /** io.github.whdt.db.view.ViewDocument */
        ViewDocument: {
            name: string;
            predicate?: components["schemas"]["TagPredicate"];
            groupByKeys?: string[];
        };
        /**
         * io.github.whdt.core.hdt.view.ViewResult
         * @description Result of executing a View. Either a flat list of matching properties or a grouped result keyed by a tag value. Observed serialized shape of ViewResult.Grouped:
         *       {"type":"grouped","key":"<groupByKey>","buckets":[[<tagValue_or_null>,{"type":"flat","properties":[...]}],...]}
         *     The buckets field is a list of [key, flat-result] pairs (BucketListSerializer) to support null bucket keys.
         */
        ViewResult: components["schemas"]["ViewResult-flat"] | components["schemas"]["ViewResult-grouped"];
        /** ViewResult-flat */
        "ViewResult-flat": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "flat";
            properties?: components["schemas"]["property"][];
        };
        /** ViewResult-grouped */
        "ViewResult-grouped": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "grouped";
            key: string;
            /** @description List of [bucketKey, ViewResult.Flat] pairs; bucketKey may be null for properties with no value for the groupByKey tag. */
            buckets: [
                string | null,
                components["schemas"]["ViewResult-flat"]
            ][];
        };
        /** io.github.whdt.routing.view.ExecuteScopeRequest */
        ExecuteScopeRequest: {
            /** @description HDT IDs to execute against. Empty or absent means all HDTs. */
            hdtIds?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type TagPredicate = components['schemas']['TagPredicate'];
export type TagPredicateEq = components['schemas']['TagPredicate-eq'];
export type TagPredicateIn = components['schemas']['TagPredicate-in'];
export type TagPredicateHas = components['schemas']['TagPredicate-has'];
export type TagPredicateAnd = components['schemas']['TagPredicate-and'];
export type TagPredicateOr = components['schemas']['TagPredicate-or'];
export type TagPredicateNot = components['schemas']['TagPredicate-not'];
export type PropertyComparisonDto = components['schemas']['PropertyComparisonDto'];
export type PropertiesByComparisonsRequestDto = components['schemas']['PropertiesByComparisonsRequestDto'];
export type MqttPhysicalInterface = components['schemas']['mqtt-physical-interface'];
export type PhysicalInterfaceImpl = components['schemas']['physical-interface-impl'];
export type PhysicalInterface = components['schemas']['PhysicalInterface'];
export type DigitalInterfaceImpl = components['schemas']['digital-interface-impl'];
export type HttpDigitalInterface = components['schemas']['http-digital-interface'];
export type MqttDigitalInterface = components['schemas']['mqtt-digital-interface'];
export type DigitalInterface = components['schemas']['DigitalInterface'];
export type Storage = components['schemas']['Storage'];
export type HumanDigitalTwinDocument = components['schemas']['HumanDigitalTwinDocument'];
export type Model = components['schemas']['model'];
export type HumanDigitalTwin = components['schemas']['human-digital-twin'];
export type ModelDocument = components['schemas']['ModelDocument'];
export type PropertyDocument = components['schemas']['PropertyDocument'];
export type PropertyEventMetadata = components['schemas']['PropertyEventMetadata'];
export type BooleanValue = components['schemas']['boolean-value'];
export type DoubleValue = components['schemas']['double-value'];
export type EmptyValue = components['schemas']['empty-value'];
export type FloatValue = components['schemas']['float-value'];
export type IntValue = components['schemas']['int-value'];
export type LongValue = components['schemas']['long-value'];
export type StringValue = components['schemas']['string-value'];
export type PropertyValue = components['schemas']['PropertyValue'];
export type Coding = components['schemas']['Coding'];
export type PropertyObservationDocument = components['schemas']['PropertyObservationDocument'];
export type PropertyObservation = components['schemas']['PropertyObservation'];
export type Property = components['schemas']['property'];
export type PropertySpecEntry = components['schemas']['PropertySpecEntry'];
export type ModelSpecEntry = components['schemas']['ModelSpecEntry'];
export type HdtSpecResponse = components['schemas']['HdtSpecResponse'];
export type PropertySnapshotEntry = components['schemas']['PropertySnapshotEntry'];
export type TaskPropertySnapshotEntry = components['schemas']['TaskPropertySnapshotEntry'];
export type PropertyValuesRequest = components['schemas']['PropertyValuesRequest'];
export type PropertyStatsRequest = components['schemas']['PropertyStatsRequest'];
export type PropertyStatsPerHdt = components['schemas']['PropertyStatsPerHdt'];
export type PropertyComparison = components['schemas']['PropertyComparison'];
export type PropertiesByComparisonsAggregateRequest = components['schemas']['PropertiesByComparisonsAggregateRequest'];
export type EventMatch = components['schemas']['EventMatch'];
export type PropertiesByComparisonsAggregateResponse = components['schemas']['PropertiesByComparisonsAggregateResponse'];
export type PropertyPopulationStats = components['schemas']['PropertyPopulationStats'];
export type ComparisonSearchResult = components['schemas']['ComparisonSearchResult'];
export type CohortPropertyCell = components['schemas']['CohortPropertyCell'];
export type CohortRow = components['schemas']['CohortRow'];
export type CohortResult = components['schemas']['CohortResult'];
export type HdtsByModelRequestDto = components['schemas']['HdtsByModelRequestDto'];
export type ModelAvailability = components['schemas']['ModelAvailability'];
export type HdtModelAvailability = components['schemas']['HdtModelAvailability'];
export type View = components['schemas']['View'];
export type ViewDocument = components['schemas']['ViewDocument'];
export type ViewResult = components['schemas']['ViewResult'];
export type ViewResultFlat = components['schemas']['ViewResult-flat'];
export type ViewResultGrouped = components['schemas']['ViewResult-grouped'];
export type ExecuteScopeRequest = components['schemas']['ExecuteScopeRequest'];
export type $defs = Record<string, never>;
export interface operations {
    "hdts/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All Human Digital Twins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanDigitalTwinDocument"][];
                };
            };
        };
    };
    "hdts/put": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The Representation of a Human Digital Twin */
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"];
            };
        };
        responses: {
            /** @description HumanDigitalTwin created or updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanDigitalTwinDocument"];
                };
            };
        };
    };
    "hdts/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The Representation of a Human Digital Twin */
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"];
            };
        };
        responses: {
            /** @description HumanDigitalTwin created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanDigitalTwinDocument"];
                };
            };
        };
    };
    "hdts/{id}/get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human Digital Twin found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanDigitalTwinDocument"];
                };
            };
            /** @description Human Digital Twin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Human Digital Twin */
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"];
            };
        };
        responses: {
            /** @description Human Digital Twin updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanDigitalTwinDocument"];
                };
            };
            /** @description Human Digital Twin to update not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human Digital Twin removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Human Digital Twin to remove not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human Digital Twin Models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDocument"][];
                };
            };
            /** @description Human Digital Twin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Human Digital Twin Observations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyObservationDocument"][];
                };
            };
            /** @description Human Digital Twin or Observations not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full HDT spec */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HdtSpecResponse"];
                };
            };
            /** @description Missing HDT id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description HDT or associated data not found */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/snapshot/by-task": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description By-task snapshot entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPropertySnapshotEntry"][];
                };
            };
            /** @description Missing HDT id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertySnapshotEntry"][];
                };
            };
            /** @description Missing HDT id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description HDT or property specs not found */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/batch/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"][];
            };
        };
        responses: {
            /** @description Human Digital Twins updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Update failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "hdts/batch/insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["human-digital-twin"][];
            };
        };
        responses: {
            /** @description Human Digital Twins inserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insertion failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "models/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All Models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDocument"][];
                };
            };
        };
    };
    "models/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The updated Model */
        requestBody: {
            content: {
                "application/json": components["schemas"]["model"];
            };
        };
        responses: {
            /** @description Upserted Successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to upsert Model */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "models/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The representation of an HDT's Model */
        requestBody: {
            content: {
                "application/json": components["schemas"]["model"];
            };
        };
        responses: {
            /** @description Created Successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDocument"];
                };
            };
        };
    };
    "models/batch/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The list of HDT Models */
        requestBody: {
            content: {
                "application/json": components["schemas"]["model"][];
            };
        };
        responses: {
            /** @description Upserted Successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to upsert Models */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "models/batch/insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The list of HDT Models */
        requestBody: {
            content: {
                "application/json": components["schemas"]["model"][];
            };
        };
        responses: {
            /** @description Created Successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to create Models */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "properties/get": {
        parameters: {
            query?: {
                modelId?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Property specs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDocument"][];
                };
            };
            /** @description Missing HDT id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "properties/batch/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description List of Property specs */
        requestBody: {
            content: {
                "application/json": components["schemas"]["property"][];
            };
        };
        responses: {
            /** @description Property specs upserted successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing HDT id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to upsert property specs */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "properties/{propertyId}/tags/put": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                propertyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Tags replaced; returns the new tag map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Missing path parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Property not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to update tags */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "properties/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Distinct property names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    "observations/batch/insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A list of PropertyObservation */
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyObservation"][];
            };
        };
        responses: {
            /** @description Observations created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error creating observations */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/property": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagPredicate"];
            };
        };
        responses: {
            /** @description Matching Property specs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDocument"][];
                };
            };
            /** @description Malformed TagPredicate body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Query failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/event/values/byId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyValuesRequest"][];
            };
        };
        responses: {
            /** @description POST /query/event/values/valuesById response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyObservationDocument"][];
                };
            };
            /** @description POST /query/event/values/valuesById response 400 if empty request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/event/values/byName": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyValuesRequest"][];
            };
        };
        responses: {
            /** @description POST /query/event/values/valuesByName response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyObservationDocument"][];
                };
            };
            /** @description POST /query/event/values/valuesByName response 400 if empty request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/event/values/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyValuesRequest"][];
            };
        };
        responses: {
            /** @description POST /query/event/values/history response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyObservationDocument"][];
                };
            };
            /** @description POST /query/event/values/history response 400 if empty request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/event/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyStatsRequest"];
            };
        };
        responses: {
            /** @description POST /query/event/stats response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyStatsPerHdt"][];
                };
            };
        };
    };
    "views/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All Views */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewDocument"][];
                };
            };
        };
    };
    "views/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The View spec to store */
        requestBody: {
            content: {
                "application/json": components["schemas"]["View"];
            };
        };
        responses: {
            /** @description View created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewDocument"];
                };
            };
        };
    };
    "views/{name}/get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description View found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewDocument"];
                };
            };
            /** @description View not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "views/{name}/put": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** @description The updated View spec */
        requestBody: {
            content: {
                "application/json": components["schemas"]["View"];
            };
        };
        responses: {
            /** @description View upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewDocument"];
                };
            };
        };
    };
    "views/{name}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description View deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description View not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "views/{name}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        /** @description Optional scope — which HDT IDs to execute against */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExecuteScopeRequest"];
            };
        };
        responses: {
            /** @description ViewResult per HDT id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ViewResult"];
                    };
                };
            };
            /** @description View not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "query/event/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PropertiesByComparisonsRequestDto"];
            };
        };
        responses: {
            /** @description POST /query/event/comparison response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonSearchResult"];
                };
            };
        };
    };
    "query/cohort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PropertiesByComparisonsRequestDto"];
            };
        };
        responses: {
            /** @description POST /query/cohort response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CohortResult"];
                };
            };
        };
    };
    "query/hdts/by-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["HdtsByModelRequestDto"];
            };
        };
        responses: {
            /** @description POST /query/hdts/by-model response 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HdtModelAvailability"][];
                };
            };
        };
    };
}
